// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	camp "campyuk-api/features/camp"

	mock "github.com/stretchr/testify/mock"
)

// CampData is an autogenerated mock type for the CampData type
type CampData struct {
	mock.Mock
}

// Add provides a mock function with given fields: userID, newCamp
func (_m *CampData) Add(userID uint, newCamp camp.Core) error {
	ret := _m.Called(userID, newCamp)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, camp.Core) error); ok {
		r0 = rf(userID, newCamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: userID, campID
func (_m *CampData) Delete(userID uint, campID uint) error {
	ret := _m.Called(userID, campID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, campID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: userID, role, campID
func (_m *CampData) GetByID(userID uint, role string, campID uint) (camp.Core, error) {
	ret := _m.Called(userID, role, campID)

	var r0 camp.Core
	if rf, ok := ret.Get(0).(func(uint, string, uint) camp.Core); ok {
		r0 = rf(userID, role, campID)
	} else {
		r0 = ret.Get(0).(camp.Core)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string, uint) error); ok {
		r1 = rf(userID, role, campID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: userID, role
func (_m *CampData) List(userID uint, role string) ([]camp.Core, error) {
	ret := _m.Called(userID, role)

	var r0 []camp.Core
	if rf, ok := ret.Get(0).(func(uint, string) []camp.Core); ok {
		r0 = rf(userID, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]camp.Core)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(userID, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestAdmin provides a mock function with given fields: userID, campID
func (_m *CampData) RequestAdmin(userID uint, campID uint) error {
	ret := _m.Called(userID, campID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint) error); ok {
		r0 = rf(userID, campID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: userID, campID, updateCamp
func (_m *CampData) Update(userID uint, campID uint, updateCamp camp.Core) error {
	ret := _m.Called(userID, campID, updateCamp)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, uint, camp.Core) error); ok {
		r0 = rf(userID, campID, updateCamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCampData interface {
	mock.TestingT
	Cleanup(func())
}

// NewCampData creates a new instance of CampData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCampData(t mockConstructorTestingTNewCampData) *CampData {
	mock := &CampData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
