// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PaymentGateway is an autogenerated mock type for the PaymentGateway type
type PaymentGateway struct {
	mock.Mock
}

// ChargeTransaction provides a mock function with given fields: orderID, grossAmt, bank
func (_m *PaymentGateway) ChargeTransaction(orderID string, grossAmt int, bank string) (string, error) {
	ret := _m.Called(orderID, grossAmt, bank)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, int, string) string); ok {
		r0 = rf(orderID, grossAmt, bank)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, string) error); ok {
		r1 = rf(orderID, grossAmt, bank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPaymentGateway interface {
	mock.TestingT
	Cleanup(func())
}

// NewPaymentGateway creates a new instance of PaymentGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPaymentGateway(t mockConstructorTestingTNewPaymentGateway) *PaymentGateway {
	mock := &PaymentGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
